# SPDX-FileCopyrightText: 2025 Cosmatic Drift contributors
# SPDX-FileCopyrightText: 2025 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
#
# SPDX-License-Identifier: MIT

# - type: department
#   id: HighCommand
#   name: department-HighCommand
#   description: department-HighCommand-description
#   color: "#334E6D"
#   weight: 90
#   primary: false # This is done to make tests pass
#   roles:
#   - Captain
#   - HeadOfPersonnel
