- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  # - Box # Vestige: Derotated Map
  - Elkridge
  # - Fland # Vestige: Derotated Map
  - Marathon
  # - Oasis # Vestige: Derotated Map
  - Packed
  - Plasma
  # - Reach # Vestige: Derotated Map
  # - Exo # Vestige: Derotated Map
