# SPDX-FileCopyrightText: 2025 Wizards Den contributors
# SPDX-FileCopyrightText: 2025 Sector Vestige contributors (modifications)
# SPDX-FileCopyrightText: 2022 Cheackraze <71046427+Cheackraze@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 OldDanceJacket <98985560+OldDanceJacket@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Rane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 brainfood1183 <113240905+brainfood1183@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 metalgearsloth <comedian_vs_clown@hotmail.com>
# SPDX-FileCopyrightText: 2023 Checkraze <71046427+Cheackraze@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 2023 Scribbles0 <91828755+Scribbles0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 TsjipTsjip <19798667+TsjipTsjip@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Ubaser <134914314+UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Golinth <amh2023@gmail.com>
# SPDX-FileCopyrightText: 2024 IProduceWidgets <107586145+IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Jacob Scott <scott@wearejacob.com>
# SPDX-FileCopyrightText: 2024 Southbridge <7013162+southbridge-fur@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 TytosB <54259736+TytosB@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 spanky-spanky <scott@wearejacob.com>
# SPDX-FileCopyrightText: 2025 Deerstop <edainturner@gmail.com>
# SPDX-FileCopyrightText: 2025 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 KravinDes <cib20@humboldt.edu>
# SPDX-FileCopyrightText: 2025 ReboundQ3 <ReboundQ3@gmail.com>
# SPDX-FileCopyrightText: 2025 Rellu225 <1blackrilfe1@gmail.com>
# SPDX-FileCopyrightText: 2025 Spanky <scott@wearejacob.com>
# SPDX-FileCopyrightText: 2025 Spessmann <156740760+Spessmann@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 TastelessMAX <32107012+TastelessMAX@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 compilatron <40789662+jbox144@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 tanuko <signar2005@gmail.com>
# SPDX-FileCopyrightText: 2025 qu4drivium <aaronholiver@outlook.com>
#
# SPDX-License-Identifier: MIT

- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  # - Box # Vestige: Derotated Map
  - Elkridge
  # - Fland # Vestige: Derotated Map
  - Marathon
  # - Oasis # Vestige: Derotated Map
  - Packed
  - Plasma
  # - Reach # Vestige: Derotated Map
  # - Exo # Vestige: Derotated Map
