- type: job
  id: SeniorCourier
  name: job-name-senior-courier
  description: job-description-senior-courier
  playTimeTracker: JobSeniorCourier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 #3 hrs
  startingGear: SeniorCourierGear
  icon: "JobIconSeniorCourier"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage

- type: startingGear
  id: SeniorCourierGear
  equipment:
    id: SeniorCourierPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool

- type: chameleonOutfit
  id: SeniorCourierChameleonOutfit
  job: SeniorCourier
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterCargo
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesFingerless
