name: "Labels: Awaiting Changes"

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_review:
    types: [submitted]

jobs:
  awaiting_changes:
    if: ${{ github.event.review.state == 'CHANGES_REQUESTED' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add Awaiting Changes label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "S: Awaiting Changes"
      - name: Remove Needs Review label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "S: Needs Review"
      - name: Remove Approved label if present
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "S: Approved"
